### ISSUE TITLE
Fresh install 

### ISSUE THREAD

**Issue by dockillborn** [Earu/EasyChat#120] opened 2024-02-10 14:30 UTC
addons/easychat-master/lua/easychat/client/settings.lua:864: attempt to get length of local 'emote_name' (a nil value)
stack traceback:
	addons/easychat-master/lua/easychat/easychat.lua:98: in function '__len'
	addons/easychat-master/lua/easychat/client/settings.lua:864: in function 'build_emote_tag'
	addons/easychat-master/lua/easychat/client/settings.lua:1028: in function 'build_usergroup_list'
	addons/easychat-master/lua/easychat/client/settings.lua:1082: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:124: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function 'xpcall'
	addons/easychat-master/lua/easychat/easychat.lua:97: in function 'SafeHookRun'
	addons/easychat-master/lua/easychat/server_config.lua:313: in function 'func'
	lua/includes/extensions/net.lua:38: in function <lua/includes/extensions/net.lua:23>

**Comment by dockillborn** [comment] 2024-02-10 14:48
I cloned this to my addons folder. I haven't changed anything in code or the data folder. I tried to add the user groups manually but that didnt work so revert that back. 
I don't know if this is helpful but I tried it with our addon list and no addons and it does the same thing
my addon list
administration-stick
easychat
gfconsole
map_vote
onyxstore
pixelui
prometheus
vcmod

**Comment by dockillborn** [comment] 2024-02-11 14:01
@Earu I cant use the built in setup new rank button. When manual creating a tag under server_config.lua with the example you have in place and changing "players" to "owner". I type in chat and I get this console error. The chat tag works but with this error.

addons/easychat-master/lua/easychat/easychat.lua:1864: attempt to get length of field 'EmoteProvider' (a nil value)
stack traceback:
	addons/easychat-master/lua/easychat/easychat.lua:1635: in function '__len'
	addons/easychat-master/lua/easychat/easychat.lua:1864: in function <addons/easychat-master/lua/easychat/easychat.lua:1814>
	[C]: in function 'xpcall'
	addons/easychat-master/lua/easychat/easychat.lua:1634: in function 'GlobalAddText'
	addons/easychat-master/lua/easychat/easychat.lua:1960: in function 'AddText'
	addons/easychat-master/lua/easychat/easychat.lua:3060: in function 'Run'
	addons/easychat-master/lua/easychat/networking.lua:431: in function 'ReceiveGlobalMessage'
	addons/easychat-master/lua/easychat/networking.lua:471: in function 'receive'
	addons/easychat-master/lua/easychat/networking.lua:474: in function 'func'
	lua/includes/extensions/net.lua:38: in function <lua/includes/extensions/net.lua:23>: t

**Comment by Earu** [comment] 2024-06-11 18:39
Closing because can't reproduce.

**Closed by Earu** 2024-06-11 18:39 UTC
